// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxutnizqfrhtzrzmjlmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4dXRuaXpxZnJodHpyem1qbG1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNzc4MzIsImV4cCI6MjA3MDc1MzgzMn0.qvIp-71GuU3018SIB031PyfKZY6VJ3-CRFa8s-XiAWc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});